version: "3.8"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    links:
      - php-fpm

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
